export const thirdDeclensionAdjectives = [
  { base: "acer", fem: "acris", neut: "acre", terminations: "three", comparative: "acrior", superlative: "acerrimus" },
  { base: "altus", fem: "alta", neut: "altum", terminations: "three", comparative: "altior", superlative: "altissimus" },
  { base: "audax", fem: "audax", neut: "audax", terminations: "one", comparative: "audacior", superlative: "audacissimus" },
  { base: "brevis", fem: "brevis", neut: "breve", terminations: "two", comparative: "brevior", superlative: "brevissimus" },
  { base: "celsus", fem: "celsa", neut: "celsum", terminations: "three", comparative: "celsior", superlative: "celssimus" },
  { base: "celer", fem: "celer", neut: "celere", terminations: "two", comparative: "celerior", superlative: "celerrimus" },
  { base: "clarus", fem: "clara", neut: "clarum", terminations: "three", comparative: "clarior", superlative: "clarissimus" },
  { base: "constans", fem: "constans", neut: "constans", terminations: "one", comparative: "constantior", superlative: "constantissimus" },
  { base: "difficilis", fem: "difficilis", neut: "difficile", terminations: "two", comparative: "difficilior", superlative: "difficillimus" },
  { base: "dulcis", fem: "dulcis", neut: "dulce", terminations: "two", comparative: "dulcior", superlative: "dulcissimus" },
  { base: "facilis", fem: "facilis", neut: "facile", terminations: "two", comparative: "facilior", superlative: "facillimus" },
  { base: "fortis", fem: "fortis", neut: "forte", terminations: "two", comparative: "fortior", superlative: "fortissimus" },
  { base: "gravis", fem: "gravis", neut: "grave", terminations: "two", comparative: "gravior", superlative: "gravissimus" },
  { base: "horridus", fem: "horrida", neut: "horridum", terminations: "three", comparative: "horridior", superlative: "horridissimus" },
  { base: "humilis", fem: "humilis", neut: "humile", terminations: "two", comparative: "humilior", superlative: "humillimus" },
  { base: "ingeniosus", fem: "ingeniosa", neut: "ingeniosum", terminations: "three", comparative: "ingeniosior", superlative: "ingeniosissimus" },
  { base: "levis", fem: "levis", neut: "leve", terminations: "two", comparative: "levior", superlative: "levissimus" },
  { base: "liber", fem: "liber", neut: "libere", terminations: "two", comparative: "liberior", superlative: "liberrimus" },
  { base: "minutus", fem: "minuta", neut: "minutum", terminations: "three", comparative: "minutior", superlative: "minutissimus" },
  { base: "novus", fem: "nova", neut: "novum", terminations: "three", comparative: "novior", superlative: "novissimus" },
  { base: "obscurus", fem: "obscura", neut: "obscurum", terminations: "three", comparative: "obscurior", superlative: "obscurissimus" },
  { base: "perterritus", fem: "perterrita", neut: "perterritum", terminations: "three", comparative: "perterritior", superlative: "perterritissimus" },
  { base: "potens", fem: "potens", neut: "potens", terminations: "one", comparative: "potentior", superlative: "potentissimus" },
  { base: "prudens", fem: "prudens", neut: "prudens", terminations: "one", comparative: "prudentior", superlative: "prudentissimus" },
  { base: "pulcher", fem: "pulchra", neut: "pulchrum", terminations: "three", comparative: "pulchrior", superlative: "pulcherrimus" },
  { base: "similis", fem: "similis", neut: "simile", terminations: "two", comparative: "similior", superlative: "simillimus" },
  { base: "stabilis", fem: "stabilis", neut: "stabile", terminations: "two", comparative: "stabilior", superlative: "stabilissimus" },
  { base: "tenuis", fem: "tenuis", neut: "tenue", terminations: "two", comparative: "tenuior", superlative: "tenuissimus" },
  { base: "tristis", fem: "tristis", neut: "triste", terminations: "two", comparative: "tristior", superlative: "tristissimus" },
  { base: "verus", fem: "vera", neut: "verum", terminations: "three", comparative: "verior", superlative: "verissimus" },
  { base: "vividus", fem: "vivida", neut: "vividum", terminations: "three", comparative: "vividior", superlative: "vividissimus" },
  { base: "vivus", fem: "viva", neut: "vivum", terminations: "three", comparative: "vivior", superlative: "vivissimus" }
].map(lemma => {
    
})