import { getStem } from "../utils/stem.js"

export const firstDeclensionNouns = [
  { nom: "puella", gen: "puellae" },
  { nom: "via", gen: "viae" },
  { nom: "patria", gen: "patriae" },
  { nom: "aqua", gen: "aquae" },
  { nom: "cura", gen: "curae" },
  { nom: "fortuna", gen: "fortunae" },
  { nom: "terra", gen: "terrae" },
  { nom: "silva", gen: "silvae" },
  { nom: "villa", gen: "villae" },
  { nom: "ira", gen: "irae" },
  { nom: "vita", gen: "vitae" },
  { nom: "forma", gen: "formae" },
  { nom: "poena", gen: "poenae" },
  { nom: "fabula", gen: "fabulae" },
  { nom: "porta", gen: "portae" },
  { nom: "mensa", gen: "mensae" },
  { nom: "insula", gen: "insulae" },
  { nom: "gloria", gen: "gloriae" },
  { nom: "hora", gen: "horae" },
  { nom: "fama", gen: "famae" },
  { nom: "causa", gen: "causae" },
  { nom: "copia", gen: "copiae" },
  { nom: "nauta", gen: "nautae" },
  { nom: "agricola", gen: "agricolae" },
  { nom: "poeta", gen: "poetae" },
  { nom: "sententia", gen: "sententiae" },
  { nom: "victoria", gen: "victoriae" },
  { nom: "pecunia", gen: "pecuniae" },
  { nom: "iniuria", gen: "iniuriae" },
  { nom: "rosa", gen: "rosae" },
  { nom: "unda", gen: "undae" },
  { nom: "umbra", gen: "umbrae" },
  { nom: "bestia", gen: "bestiae" },
  { nom: "filia", gen: "filiae" },
  { nom: "dea", gen: "deae" },
  { nom: "epistula", gen: "epistulae" },
  { nom: "figura", gen: "figurae" },
  { nom: "lacrima", gen: "lacrimae" },
  { nom: "lingua", gen: "linguae" },
  { nom: "littera", gen: "litterae" },
  { nom: "memoria", gen: "memoriae" },
  { nom: "natura", gen: "naturae" },
  { nom: "officina", gen: "officinae" },
  { nom: "philosophia", gen: "philosophiae" },
  { nom: "praeda", gen: "praedae" },
  { nom: "regina", gen: "reginae" },
  { nom: "scientia", gen: "scientiae" },
  { nom: "societas", gen: "societatis" }, // irregular genitive
  { nom: "statua", gen: "statuae" },
  { nom: "taberna", gen: "tabernae" },
  { nom: "tempestas", gen: "tempestatis" }, // irregular genitive
  { nom: "umbella", gen: "umbellae" },
  { nom: "uxor", gen: "uxoris" }, // irregular genitive
  { nom: "verba", gen: "verbae" },
  { nom: "victima", gen: "victimae" },
  { nom: "virga", gen: "virgae" },
  { nom: "vulnera", gen: "vulnerae" },
  { nom: "curae", gen: "curae" },
  { nom: "arma", gen: "armae" },
  { nom: "aula", gen: "aulae" },
  { nom: "bona", gen: "bonae" },
  { nom: "cella", gen: "cellae" },
  { nom: "clausa", gen: "clausae" },
  { nom: "coquina", gen: "coquinae" },
  { nom: "corona", gen: "coronae" },
  { nom: "cultura", gen: "culturae" },
  { nom: "disciplina", gen: "disciplinae" },
  { nom: "domina", gen: "dominae" },
  { nom: "familia", gen: "familiae" },
  { nom: "fenestra", gen: "fenestrae" },
  { nom: "flamma", gen: "flammae" },
  { nom: "forma", gen: "formae" },
  { nom: "herba", gen: "herbae" },
  { nom: "historia", gen: "historiae" },
  { nom: "iniqua", gen: "iniquae" },
  { nom: "iustitia", gen: "iustitiae" },
  { nom: "laus", gen: "laudis" }, // irregular genitive
  { nom: "materia", gen: "materiae" },
  { nom: "mora", gen: "morae" },
  { nom: "noxa", gen: "noxae" },
  { nom: "opera", gen: "operae" },
  { nom: "ora", gen: "orae" },
  { nom: "pagina", gen: "paginae" },
  { nom: "parva", gen: "parvae" },
  { nom: "pugna", gen: "pugnae" },
  { nom: "sella", gen: "sellae" },
  { nom: "sera", gen: "serae" },
  { nom: "specula", gen: "speculae" },
  { nom: "stella", gen: "stellae" },
  { nom: "tela", gen: "telae" }
].map(lemma => {
  let stem = getStem(lemma.gen, 2);
  const lemmaNom = lemma.nom;
  const lemmaGen = lemma.gen;
  return {
    forms: {
        nom: { sg: lemmaNom, pl: stem + "ae" },
        gen: { sg: lemmaGen, pl: stem + "arum" },
        dat: { sg: stem + "ae", pl: stem + "is" },
        acc: { sg: stem + "am", pl: stem + "as" },
        abl: { sg: stem + "a", pl: stem + "is" }
    }
}});
